# Generated by Django 4.2 on 2023-04-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=800, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/ед.')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotobase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photobase/%Y/%m/%d', verbose_name='Фото 1')),
                ('image2', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 2')),
                ('image3', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 3')),
                ('image4', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 4')),
                ('image5', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 5')),
                ('image6', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 6')),
                ('image7', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 7')),
                ('image8', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 8')),
                ('image9', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 9')),
                ('image10', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 10')),
            ],
            options={
                'verbose_name': 'Блок фотографий продукта',
                'verbose_name_plural': 'Блоки фотографий продуктов',
                'db_table': 'product_photobase',
            },
        ),
        migrations.CreateModel(
            name='ReviewPhotobase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photobase/%Y/%m/%d', verbose_name='Фото 1')),
                ('image2', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 2')),
                ('image3', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 3')),
                ('image4', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 4')),
                ('image5', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 5')),
                ('image6', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 6')),
                ('image7', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 7')),
                ('image8', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 8')),
                ('image9', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 9')),
                ('image10', models.ImageField(blank=True, upload_to='photobase/%Y/%m/%d', verbose_name='Фото 10')),
            ],
            options={
                'verbose_name': 'Блок фотографий отзыва',
                'verbose_name_plural': 'Блоки фотографий отзывов',
                'db_table': 'review_photobase',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=800, verbose_name='Описание')),
                ('avatar', models.ImageField(upload_to='shops/avatars/%Y/%m/%d/', verbose_name='Аватар')),
                ('header', models.ImageField(upload_to='shops/headers/%Y/%m/%d', verbose_name='Шапка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', related_query_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('text', models.CharField(blank=True, max_length=800, verbose_name='Текст')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', related_query_name='review', to='backend.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_reviews', related_query_name='shop_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв о магазине',
                'verbose_name_plural': 'Отзывы о магазине',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('text', models.CharField(blank=True, max_length=800, verbose_name='Текст')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='backend.deal')),
                ('photobase', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='backend.reviewphotobase')),
            ],
            options={
                'verbose_name': 'Отзыв о продукте',
                'verbose_name_plural': 'Отзывы о продукте',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=800, verbose_name='Описание')),
                ('composition', models.CharField(blank=True, max_length=400, verbose_name='Состав')),
                ('discount', models.PositiveSmallIntegerField(blank=True, verbose_name='Скидка')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Количество')),
                ('weight', models.IntegerField(blank=True, verbose_name='Вес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date_manufacture', models.DateField(blank=True, verbose_name='Дата изготовления')),
                ('shelf_life', models.CharField(blank=True, max_length=50, verbose_name='Срок хранения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='backend.category')),
                ('photobase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', related_query_name='product', to='backend.productphotobase')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='product', to='backend.shop')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', related_query_name='deal', to='backend.product'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', related_query_name='deal', to=settings.AUTH_USER_MODEL),
        ),
    ]
