# Generated by Django 4.2 on 2023-04-07 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', related_query_name='deal', to='backend.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', related_query_name='deal', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='backend.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photobase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', related_query_name='product', to='backend.productphotobase', verbose_name='Блок фотографий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', related_query_name='product', to='backend.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='backend.deal', verbose_name='Сделка'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='photobase',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='review', to='backend.reviewphotobase', verbose_name='Блок фотографий'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', related_query_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', related_query_name='review', to='backend.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_reviews', related_query_name='shop_review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
